org: culmi05
service: api-proyecciones

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::637458465934:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_CINES: t_cines
    TABLE_NAME_CARTELERA: t_cartelera
    TABLE_NAME_PELICULAS: t_peliculas
    TABLE_NAME_PROYECCIONES: t_proyecciones

functions:
  AddProyection:
    handler: AddProyeccion.lambda_handler
    events:
      - http:
          path: /proyecciones/agregar
          method: post
          cors: true
          integration: lambda

  UpdateProyection:
    handler: UpdateProyeccion.lambda_handler
    events:
      - http:
          path: /proyecciones/actualizar
          method: put
          cors: true
          integration: lambda

  DeleteProyection:
    handler: DeleteProyeccion.lambda_handler
    events:
      - http:
          path: /proyecciones/eliminar
          method: delete
          cors: true
          integration: lambda
